// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2026 Pierre Poissinger

package tui

import (
	"strings"
	"unicode/utf8"
)

// Key events are represented as raw terminal strings + helper constants.
// The TUI receives raw bytes from the terminal and decodes them into
// key string representations. Components receive these key strings
// via HandleInput and can use matchesKey to check for specific keys.

// DecodeResult holds a decoded key string and the bytes consumed.
type DecodeResult struct {
	Key      string // decoded key representation
	Consumed int    // bytes consumed
}

// Key constants used by matchesKey for comparing decoded keys.
const (
	KeyEnter      = "enter"
	KeyBackspace  = "backspace"
	KeyDelete     = "delete"
	KeyTab        = "tab"
	KeyEscape     = "escape"
	KeyUp         = "up"
	KeyDown       = "down"
	KeyLeft       = "left"
	KeyRight      = "right"
	KeyHome       = "home"
	KeyEnd        = "end"
	KeyPageUp     = "pageUp"
	KeyPageDown   = "pageDown"
	KeyCtrlC      = "ctrl+c"
	KeyCtrlD      = "ctrl+d"
	KeyCtrlW      = "ctrl+w"
	KeyCtrlU      = "ctrl+u"
	KeyCtrlK      = "ctrl+k"
	KeyCtrlA      = "ctrl+a"
	KeyCtrlE      = "ctrl+e"
	KeyCtrlL      = "ctrl+l"
	KeyCtrlT      = "ctrl+t"
	KeyCtrlV      = "ctrl+v"
	KeyCtrlY      = "ctrl+y"
	KeyAltEnter   = "alt+enter"
	KeyShiftTab   = "shift+tab"
	KeyShiftUp    = "shift+up"
	KeyShiftDown  = "shift+down"
	KeyShiftLeft  = "shift+left"
	KeyShiftRight = "shift+right"

	// KeySuperV is Cmd+V (macOS) or Super+V — the paste chord a terminal forwards
	// instead of pasting itself. A terminal can only paste for you when the
	// clipboard holds text: with an image-only clipboard (a screenshot) macOS
	// disables the terminal's Paste menu item, the chord falls through to the
	// surface, and a terminal speaking the Kitty keyboard protocol reports it as
	// Cmd+V. Binding it is what makes Cmd+V paste an image (see
	// tui/editor.go:pasteFromClipboard).
	KeySuperV = "super+v"
)

// matchesKey checks if a decoded key string matches a named key.
func matchesKey(data, key string) bool {
	return data == key
}

// optionKeyAliases maps printable characters produced by common macOS
// Option-key combinations back to their alt+<base> key names. This lets
// app shortcuts work even when the terminal emits the character instead of
// an ESC-prefixed sequence.
var optionKeyAliases = map[string]string{
	"µ": "alt+m",
	"¬": "alt+l",
	"†": "alt+t",
	"ß": "alt+s",
	"©": "alt+g",
	"ç": "alt+c",
	"®": "alt+r",
	"∑": "alt+w",
	"¥": "alt+y",
	"ø": "alt+o",
	"π": "alt+p",
	"å": "alt+a",
	"ê": "alt+e",
	// Multi-agent tab navigation (T5): US-layout Option+[ / Option+] produce
	// the curly quotes, Option+1..9 the digit row below.
	"“": "alt+[",
	"‘": "alt+]",
	"¡": "alt+1",
	"™": "alt+2",
	"£": "alt+3",
	"¢": "alt+4",
	"∞": "alt+5",
	"§": "alt+6",
	"¶": "alt+7",
	"•": "alt+8",
	"ª": "alt+9",
}

// altKeyName returns the alt+<base> key name for a printable character that
// is generated by an Option-key combination, or "" if no alias is known.
func altKeyName(char string) string {
	return optionKeyAliases[char]
}

// isKeyRelease checks if a key string is a key release event (Kitty protocol).
// Kitty appends :N (press=1, repeat=2, release=3) as a modifier suffix.
// Detects both _ suffix (protocol 1) and :3 prefix (protocol 2).
func isKeyRelease(data string) bool {
	// Kitty protocol 2 release: :3 before final byte
	if strings.Contains(data, "\x1b[") && strings.Contains(data, ":3") {
		return strings.HasSuffix(data, "u") ||
			strings.HasSuffix(data, "~") ||
			strings.HasSuffix(data, "A") || stringSuffixAny(data, []string{"B", "C", "D", "H", "F"})
	}
	// Kitty protocol 1 release: _ suffix
	return strings.HasPrefix(data, "\x1b[") && strings.HasSuffix(data, "_")
}

func stringSuffixAny(s string, suffixes []string) bool {
	for _, suf := range suffixes {
		if strings.HasSuffix(s, suf) {
			return true
		}
	}
	return false
}

// decodeKeys decodes raw terminal bytes into key strings.
// Returns one key string per decoded key event.
func decodeKeys(data []byte) []string {
	var keys []string
	i := 0
	for i < len(data) {
		key, consumed := decodeOne(data, i)
		if consumed > 0 {
			if key != "" {
				keys = append(keys, key)
			}
			i += consumed
		} else {
			i++
		}
	}
	return keys
}

// decodeOne decodes a single key starting at position i.
func decodeOne(data []byte, i int) (string, int) {
	if i >= len(data) {
		return "", 0
	}
	b := data[i]

	// Control characters
	if key, ok := decodeCtrl(b); ok {
		return key, 1
	}

	// Escape sequences
	if b == 0x1b {
		return decodeESC(data, i)
	}

	// Printable ASCII
	if b < 128 {
		return string(rune(b)), 1
	}

	// UTF-8 multi-byte
	r, size := utf8.DecodeRune(data[i:])
	if r == utf8.RuneError && size == 1 {
		return "", 1
	}
	return string(r), size
}

// ctrlMap maps control bytes to named keys.
var ctrlMap = map[byte]string{
	0x03: KeyCtrlC,
	0x04: KeyCtrlD,
	0x0d: KeyEnter,
	0x0a: KeyEnter,
	0x7f: KeyBackspace,
	0x09: KeyTab,
	0x01: KeyCtrlA,
	0x05: KeyCtrlE,
	0x08: "ctrl+h",
	0x0b: "ctrl+k",
	0x0c: KeyCtrlL,
	0x14: KeyCtrlT,
	0x15: KeyCtrlU,
	0x16: KeyCtrlV,
	0x17: KeyCtrlW,
	0x19: KeyCtrlY,
	// 0x1b NOT included — handled by decodeESC
}

func decodeCtrl(b byte) (string, bool) {
	key, ok := ctrlMap[b]
	return key, ok
}

func decodeESC(data []byte, i int) (string, int) {
	if i+1 >= len(data) {
		// Bare ESC with nothing after — this IS the escape key
		return KeyEscape, 1
	}
	next := data[i+1]

	// CSI sequence: ESC [ ...
	if next == '[' {
		return decodeCSI(data, i)
	}

	if next == 'O' {
		return decodeSS3(data, i)
	}

	return decodeAltKey(data, i)
}

func decodeSS3(data []byte, i int) (string, int) {
	if i+2 >= len(data) {
		return "", 1
	}
	switch data[i+2] {
	case 'H':
		return KeyHome, 3
	case 'F':
		return KeyEnd, 3
	case 'P':
		return "f1", 3
	case 'Q':
		return "f2", 3
	case 'R':
		return "f3", 3
	case 'S':
		return "f4", 3
	}
	return "", 1
}

func decodeAltKey(data []byte, i int) (string, int) {
	next := data[i+1]
	if next < 32 || next >= 127 {
		return "", 1
	}
	r, size := utf8.DecodeRune(data[i+1:])
	return "alt+" + string(r), 1 + size
}

// csiSeq maps CSI terminal bytes to key names.
var csiSeq = map[string]string{
	"A":   KeyUp,
	"B":   KeyDown,
	"C":   KeyRight,
	"D":   KeyLeft,
	"H":   KeyHome,
	"F":   KeyEnd,
	"3~":  KeyDelete,
	"1~":  KeyHome,
	"7~":  KeyHome,
	"4~":  KeyEnd,
	"8~":  KeyEnd,
	"5~":  KeyPageUp,
	"6~":  KeyPageDown,
	"2~":  "insert",
	"15~": "f5",
	"17~": "f6",
	"18~": "f7",
	"19~": "f8",
	"20~": "f9",
	"21~": "f10",
	"23~": "f11",
	"24~": "f12",
}

// Kitty modifier bits, as reported in the numeric parameter of a CSI sequence
// (modifier = 1 + the bits below: "no modifier" is 1, ctrl is 5, ctrl+shift 6,
// super 9).
const (
	modShift    = 1
	modAlt      = 2
	modCtrl     = 4
	modSuper    = 8
	modHyper    = 16
	modMeta     = 32
	modCapsLock = 64
	modNumLock  = 128
)

// modifierNames lists the modifier bits that take part in a key name, in the
// order they are written: the order the bindings use ("ctrl+shift+v",
// "ctrl+alt+]").
var modifierNames = []struct {
	bit  int
	name string
}{
	{modCtrl, "ctrl"},
	{modAlt, "alt"},
	{modShift, "shift"},
	{modSuper, "super"},
	{modHyper, "hyper"},
	{modMeta, "meta"},
}

// csiModPrefix returns the modifier prefix for a CSI/Kitty modifier value
// (5 → "ctrl+") and whether the value could be named at all.
//
// The lock bits are ignored: they report that a lock is *on*, not that the user
// pressed a modifier, so a chord must keep its name while Caps Lock is held.
//
// ok=false means the value carries a bit this decoder has no name for, and the
// caller must then drop the key rather than emit it bare. Emitting the bare key
// is how Cmd+V became a literal "v": the protocol reports it as ESC [ 118 ; 9 u
// (9 = 1 + super), and with no case for super the modifier was silently
// discarded, leaving a printable character the editor typed into the input line.
func csiModPrefix(mod int) (string, bool) {
	bits := mod - 1 // Kitty encodes "no modifier" as 1
	if bits < 0 {
		return "", false
	}
	known := modShift | modAlt | modCtrl | modSuper | modHyper | modMeta |
		modCapsLock | modNumLock
	if bits&^known != 0 {
		return "", false
	}
	bits &^= modCapsLock | modNumLock
	if bits == 0 {
		return "", true
	}
	var b strings.Builder
	for _, m := range modifierNames {
		if bits&m.bit != 0 {
			b.WriteString(m.name)
			b.WriteByte('+')
		}
	}
	return b.String(), true
}

// withCSIModifier writes a chord's modifier into a decoded key name. ok=false
// when the modifier value cannot be named: a modified key must then be dropped
// (it is a chord we cannot identify), never reported as the bare key it was read
// from — a bare key is text as far as the editor is concerned.
func withCSIModifier(key string, mod int) (string, bool) {
	if mod <= 1 {
		return key, true
	}
	prefix, ok := csiModPrefix(mod)
	if !ok {
		return "", false
	}
	return prefix + key, true
}

// csiModifierIsShiftOnly reports whether a modifier value carries shift and no
// other modifier (locks excluded).
func csiModifierIsShiftOnly(mod int) bool {
	bits := mod - 1
	return bits&modShift != 0 && bits&^(modShift|modCapsLock|modNumLock) == 0
}

// isChordName reports whether name is a *chord* — a modifier followed by a key,
// as the decoder spells the names it emits for a modified key ("super+v",
// "ctrl+shift+m", "alt+up").
//
// Components that insert text need it: a decoded chord name reaches them through
// the same HandleInput(string) a typed character does, and it is ordinary
// printable ASCII, so without this check an unbound chord is *typed into the
// buffer* — the reported "Cmd+V inserts a v". Unmodified names ("delete",
// "insert", "pageUp", "f5") are deliberately *not* chords: those spellings are
// ordinary words a user can paste, and this check must never swallow someone's
// clipboard. What is lost is only the pre-existing cosmetic case of an unbound
// bare name being typed as text.
func isChordName(name string) bool {
	for _, m := range modifierNames {
		if strings.HasPrefix(name, m.name+"+") {
			return true
		}
	}
	return false
}

// decodeCSI decodes a CSI escape sequence starting with ESC[.
func decodeCSI(data []byte, start int) (string, int) {
	if len(data) < 3 || data[start] != 0x1b || data[start+1] != '[' {
		return "", 1
	}

	j, ok := findCSIFinalByte(data, start)
	if !ok {
		return "", 2
	}
	final := data[j]
	consumed := j - start + 1
	params := string(data[start+2 : j])

	params, mod := parseCSIModifier(params)

	if final == 'u' {
		return decodeCSIu(data, start, j, consumed, mod)
	}
	return decodeStandardCSI(params, final, mod, consumed)
}

// findCSIFinalByte locates the final byte of a CSI sequence.
// It returns the index of the final byte and true on success.
func findCSIFinalByte(data []byte, start int) (int, bool) {
	scanLimit := len(data)
	if scanLimit > start+64 {
		scanLimit = start + 64
	}

	semicolonPos := -1
	firstFinal := -1
	for pos := start + 2; pos < scanLimit; pos++ {
		b := data[pos]
		if b == ';' {
			semicolonPos = pos
			break
		}
		if isFinalByte(b) && firstFinal < 0 {
			firstFinal = pos
		}
	}

	if semicolonPos >= 0 {
		return findFinalAfterSemicolon(data, start, semicolonPos, scanLimit)
	}
	if firstFinal >= 0 {
		return firstFinal, true
	}
	return 0, false
}

// findFinalAfterSemicolon searches for the final byte after a ';' parameter separator.
func findFinalAfterSemicolon(data []byte, start, semicolonPos, scanLimit int) (int, bool) {
	for pos := semicolonPos + 1; pos < scanLimit; pos++ {
		if isFinalByte(data[pos]) {
			return pos, true
		}
	}
	return 0, false
}

// parseCSIModifier extracts the modifier value from CSI parameters and returns
// the stripped parameter string.
func parseCSIModifier(params string) (string, int) {
	idx := strings.IndexByte(params, ';')
	if idx < 0 {
		return params, 1
	}
	mod := 1
	if idx+1 < len(params) {
		if m := atoi(params[idx+1:]); m > 0 {
			mod = m
		}
	}
	params = params[:idx]
	// Strip leading digits for CSI-u lookup.
	for len(params) > 0 && params[0] >= '0' && params[0] <= '9' {
		params = params[1:]
	}
	return params, mod
}

// decodeStandardCSI decodes a non-CSI-u sequence using the csiSeq lookup table.
func decodeStandardCSI(params string, final byte, mod, consumed int) (string, int) {
	seqKey := params + string(final)
	if key, found := csiSeq[seqKey]; found {
		named, ok := withCSIModifier(key, mod)
		if !ok {
			return "", consumed
		}
		return named, consumed
	}
	if seqKey == "Z" {
		return KeyShiftTab, consumed
	}
	return "", consumed
}

// decodeCSIu decodes a Kitty CSI-u sequence (final byte = 'u').
// Formats:
//   - \x1b[A;1u (letter-based cursor keys)
//   - \x1b[OP;1u (SS3-style function keys)
//   - \x1b[3~;1u (tilde-based editing keys)
//   - \x1b[13;5u (numeric control codes with modifier)
//   - \x1b[97;1u (printable characters)
func decodeCSIu(data []byte, start, j, consumed, mod int) (string, int) {
	// Extract raw parameters from between ESC[ and the 'u' final byte
	fullParams := string(data[start+2 : j])
	codeEnd := strings.IndexByte(fullParams, ';')
	var ident string
	if codeEnd <= 0 {
		if len(fullParams) == 0 {
			return "", consumed
		}
		// No modifier part (e.g. \x1b[27u instead of \x1b[27;1u).
		// Use the entire params as the key identifier.
		ident = fullParams
	} else {
		ident = fullParams[:codeEnd] // key identifier before ';'
	}

	// 1) Letter-based identifiers: cursor keys (\x1b[A;1u) and SS3-style F-keys (\x1b[OP;1u)
	if ident[0] >= 'A' && ident[0] <= 'Z' {
		if key, ok := decodeCSIuLetterIdent(ident, mod); ok {
			return key, consumed
		}
		return "", consumed
	}

	// 2) Tilde-based codes: \x1b[3~;1u (Delete), \x1b[5~;1u (PageUp), etc.
	if key, found := csiSeq[ident]; found {
		named, ok := withCSIModifier(key, mod)
		if !ok {
			return "", consumed
		}
		return named, consumed
	}

	// 4) Numeric control codes
	code := atoi(ident)
	if key, ok := decodeCSIuNumeric(code, mod); ok {
		return key, consumed
	}
	return "", consumed
}

// decodeCSIuLetterIdent handles letter-based CSI-u key identifiers.
// Supports single-letter cursor keys (\x1b[A;1u → "up") and SS3-style
// function keys (\x1b[OP;1u → "f1").
func decodeCSIuLetterIdent(ident string, mod int) (string, bool) {
	// Single-letter cursor/editing key
	if len(ident) == 1 {
		if key, ok := csiSeq[ident]; ok {
			return withCSIModifier(key, mod)
		}
		return "", false
	}

	// SS3-style function key identifiers: OP (F1), OQ (F2), OR (F3), OS (F4)
	if len(ident) == 2 && ident[0] == 'O' && ident[1] >= 'P' && ident[1] <= 'S' {
		fkey := map[byte]string{
			'P': "f1", 'Q': "f2", 'R': "f3", 'S': "f4",
		}[ident[1]]
		return withCSIModifier(fkey, mod)
	}

	return "", false
}

// printableKeyName names the character a CSI-u code stands for. A terminal
// reports the code point *as shifted* for a shifted key, so Ctrl+Shift+V arrives
// as 86 ("V") while the bindings spell chords on the base letter
// ("ctrl+shift+v"): a shifted letter is normalised to its base letter whenever
// another modifier is part of the chord, which is what makes the documented
// ctrl+shift+v paste reachable in a Kitty-protocol terminal.
func printableKeyName(r rune, mod int) string {
	if mod > 1 && r >= 'A' && r <= 'Z' && !csiModifierIsShiftOnly(mod) {
		return strings.ToLower(string(r))
	}
	return string(r)
}

// decodeCSIuNumeric maps numeric key codes to key strings for CSI-u format.
func decodeCSIuNumeric(code, mod int) (string, bool) {
	switch {
	case code == 13:
		return withCSIModifier(KeyEnter, mod)
	case code == 27:
		// Kitty protocol may also report Escape as keycode 27 with various
		// modifiers. Regardless of modifier, treat it as Escape so the
		// wizard (and other components) can navigate back.
		return KeyEscape, true
	case code == 9:
		return withCSIModifier(KeyTab, mod)
	case code == 8 || code == 127:
		// The modifier is meaningful: terminals report Ctrl/Alt+Backspace as
		// code 127 with a modifier (kitty: ESC [ 127 ; 5 u), and the editor
		// binds "ctrl+backspace" / "alt+backspace" to word deletion. Dropping
		// it here silently downgraded those chords to a single-char delete.
		return withCSIModifier(KeyBackspace, mod)
	case code >= 32 && code <= 126:
		return withCSIModifier(printableKeyName(rune(code), mod), mod)
	}
	return "", false
}

// atoi parses a string to int, returning 0 on error.
func atoi(s string) int {
	n := 0
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c < '0' || c > '9' {
			return n
		}
		n = n*10 + int(c-'0')
	}
	return n
}
