// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2026 Pierre Poissinger

package tui

import (
	"strings"
	"unicode/utf8"
)

// Key events are represented as raw terminal strings + helper constants.
// The TUI receives raw bytes from the terminal and decodes them into
// key string representations. Components receive these key strings
// via HandleInput and can use matchesKey to check for specific keys.

// DecodeResult holds a decoded key string and the bytes consumed.
type DecodeResult struct {
	Key      string // decoded key representation
	Consumed int    // bytes consumed
}

// Key constants used by matchesKey for comparing decoded keys.
const (
	KeyEnter      = "enter"
	KeyBackspace  = "backspace"
	KeyDelete     = "delete"
	KeyTab        = "tab"
	KeyEscape     = "escape"
	KeyUp         = "up"
	KeyDown       = "down"
	KeyLeft       = "left"
	KeyRight      = "right"
	KeyHome       = "home"
	KeyEnd        = "end"
	KeyPageUp     = "pageUp"
	KeyPageDown   = "pageDown"
	KeyCtrlC      = "ctrl+c"
	KeyCtrlD      = "ctrl+d"
	KeyCtrlW      = "ctrl+w"
	KeyCtrlU      = "ctrl+u"
	KeyCtrlK      = "ctrl+k"
	KeyCtrlA      = "ctrl+a"
	KeyCtrlE      = "ctrl+e"
	KeyCtrlL      = "ctrl+l"
	KeyCtrlT      = "ctrl+t"
	KeyCtrlY      = "ctrl+y"
	KeyAltEnter   = "alt+enter"
	KeyShiftTab   = "shift+tab"
	KeyShiftUp    = "shift+up"
	KeyShiftDown  = "shift+down"
	KeyShiftLeft  = "shift+left"
	KeyShiftRight = "shift+right"
)

// matchesKey checks if a decoded key string matches a named key.
func matchesKey(data, key string) bool {
	return data == key
}

// optionKeyAliases maps printable characters produced by common macOS
// Option-key combinations back to their alt+<base> key names. This lets
// app shortcuts work even when the terminal emits the character instead of
// an ESC-prefixed sequence.
var optionKeyAliases = map[string]string{
	"µ": "alt+m",
	"¬": "alt+l",
	"†": "alt+t",
	"ß": "alt+s",
	"©": "alt+g",
	"ç": "alt+c",
	"®": "alt+r",
	"∑": "alt+w",
	"¥": "alt+y",
	"ø": "alt+o",
	"π": "alt+p",
	"å": "alt+a",
	"ê": "alt+e",
}

// altKeyName returns the alt+<base> key name for a printable character that
// is generated by an Option-key combination, or "" if no alias is known.
func altKeyName(char string) string {
	return optionKeyAliases[char]
}

// isKeyRelease checks if a key string is a key release event (Kitty protocol).
// Kitty appends :N (press=1, repeat=2, release=3) as a modifier suffix.
// Detects both _ suffix (protocol 1) and :3 prefix (protocol 2).
func isKeyRelease(data string) bool {
	// Kitty protocol 2 release: :3 before final byte
	if strings.Contains(data, "\x1b[") && strings.Contains(data, ":3") {
		return strings.HasSuffix(data, "u") ||
			strings.HasSuffix(data, "~") ||
			strings.HasSuffix(data, "A") || stringSuffixAny(data, []string{"B", "C", "D", "H", "F"})
	}
	// Kitty protocol 1 release: _ suffix
	return strings.HasPrefix(data, "\x1b[") && strings.HasSuffix(data, "_")
}

func stringSuffixAny(s string, suffixes []string) bool {
	for _, suf := range suffixes {
		if strings.HasSuffix(s, suf) {
			return true
		}
	}
	return false
}

// decodeKeys decodes raw terminal bytes into key strings.
// Returns one key string per decoded key event.
func decodeKeys(data []byte) []string {
	var keys []string
	i := 0
	for i < len(data) {
		key, consumed := decodeOne(data, i)
		if consumed > 0 {
			if key != "" {
				keys = append(keys, key)
			}
			i += consumed
		} else {
			i++
		}
	}
	return keys
}

// decodeOne decodes a single key starting at position i.
func decodeOne(data []byte, i int) (string, int) {
	if i >= len(data) {
		return "", 0
	}
	b := data[i]

	// Control characters
	if key, ok := decodeCtrl(b); ok {
		return key, 1
	}

	// Escape sequences
	if b == 0x1b {
		return decodeESC(data, i)
	}

	// Printable ASCII
	if b < 128 {
		return string(rune(b)), 1
	}

	// UTF-8 multi-byte
	r, size := utf8.DecodeRune(data[i:])
	if r == utf8.RuneError && size == 1 {
		return "", 1
	}
	return string(r), size
}

// ctrlMap maps control bytes to named keys.
var ctrlMap = map[byte]string{
	0x03: KeyCtrlC,
	0x04: KeyCtrlD,
	0x0d: KeyEnter,
	0x0a: KeyEnter,
	0x7f: KeyBackspace,
	0x09: KeyTab,
	0x01: KeyCtrlA,
	0x05: KeyCtrlE,
	0x08: "ctrl+h",
	0x0b: "ctrl+k",
	0x0c: KeyCtrlL,
	0x14: KeyCtrlT,
	0x15: KeyCtrlU,
	0x17: KeyCtrlW,
	0x19: KeyCtrlY,
	// 0x1b NOT included — handled by decodeESC
}

func decodeCtrl(b byte) (string, bool) {
	key, ok := ctrlMap[b]
	return key, ok
}

func decodeESC(data []byte, i int) (string, int) {
	if i+1 >= len(data) {
		// Bare ESC with nothing after — this IS the escape key
		return KeyEscape, 1
	}
	next := data[i+1]

	// CSI sequence: ESC [ ...
	if next == '[' {
		return decodeCSI(data, i)
	}

	if next == 'O' {
		return decodeSS3(data, i)
	}

	return decodeAltKey(data, i)
}

func decodeSS3(data []byte, i int) (string, int) {
	if i+2 >= len(data) {
		return "", 1
	}
	switch data[i+2] {
	case 'H':
		return KeyHome, 3
	case 'F':
		return KeyEnd, 3
	case 'P':
		return "f1", 3
	case 'Q':
		return "f2", 3
	case 'R':
		return "f3", 3
	case 'S':
		return "f4", 3
	}
	return "", 1
}

func decodeAltKey(data []byte, i int) (string, int) {
	next := data[i+1]
	if next < 32 || next >= 127 {
		return "", 1
	}
	r, size := utf8.DecodeRune(data[i+1:])
	return "alt+" + string(r), 1 + size
}

// csiSeq maps CSI terminal bytes to key names.
var csiSeq = map[string]string{
	"A":   KeyUp,
	"B":   KeyDown,
	"C":   KeyRight,
	"D":   KeyLeft,
	"H":   KeyHome,
	"F":   KeyEnd,
	"3~":  KeyDelete,
	"1~":  KeyHome,
	"7~":  KeyHome,
	"4~":  KeyEnd,
	"8~":  KeyEnd,
	"5~":  KeyPageUp,
	"6~":  KeyPageDown,
	"2~":  "insert",
	"15~": "f5",
	"17~": "f6",
	"18~": "f7",
	"19~": "f8",
	"20~": "f9",
	"21~": "f10",
	"23~": "f11",
	"24~": "f12",
}

// csiMod maps CSI modifier values to modifier prefixes.
func csiModPrefix(mod int) string {
	switch mod {
	case 2:
		return "shift+"
	case 3:
		return "alt+"
	case 4:
		return "alt+shift+"
	case 5:
		return "ctrl+"
	case 6:
		return "ctrl+shift+"
	case 7:
		return "ctrl+alt+"
	case 8:
		return "ctrl+alt+shift+"
	default:
		return ""
	}
}

// decodeCSI decodes a CSI escape sequence starting with ESC[.
func decodeCSI(data []byte, start int) (string, int) {
	if len(data) < 3 || data[start] != 0x1b || data[start+1] != '[' {
		return "", 1
	}

	j, ok := findCSIFinalByte(data, start)
	if !ok {
		return "", 2
	}
	final := data[j]
	consumed := j - start + 1
	params := string(data[start+2 : j])

	params, mod := parseCSIModifier(params)

	if final == 'u' {
		return decodeCSIu(data, start, j, consumed, mod)
	}
	return decodeStandardCSI(params, final, mod, consumed)
}

// findCSIFinalByte locates the final byte of a CSI sequence.
// It returns the index of the final byte and true on success.
func findCSIFinalByte(data []byte, start int) (int, bool) {
	scanLimit := len(data)
	if scanLimit > start+64 {
		scanLimit = start + 64
	}

	semicolonPos := -1
	firstFinal := -1
	for pos := start + 2; pos < scanLimit; pos++ {
		b := data[pos]
		if b == ';' {
			semicolonPos = pos
			break
		}
		if isFinalByte(b) && firstFinal < 0 {
			firstFinal = pos
		}
	}

	if semicolonPos >= 0 {
		return findFinalAfterSemicolon(data, start, semicolonPos, scanLimit)
	}
	if firstFinal >= 0 {
		return firstFinal, true
	}
	return 0, false
}

// findFinalAfterSemicolon searches for the final byte after a ';' parameter separator.
func findFinalAfterSemicolon(data []byte, start, semicolonPos, scanLimit int) (int, bool) {
	for pos := semicolonPos + 1; pos < scanLimit; pos++ {
		if isFinalByte(data[pos]) {
			return pos, true
		}
	}
	return 0, false
}

// parseCSIModifier extracts the modifier value from CSI parameters and returns
// the stripped parameter string.
func parseCSIModifier(params string) (string, int) {
	idx := strings.IndexByte(params, ';')
	if idx < 0 {
		return params, 1
	}
	mod := 1
	if idx+1 < len(params) {
		if m := atoi(params[idx+1:]); m > 0 {
			mod = m
		}
	}
	params = params[:idx]
	// Strip leading digits for CSI-u lookup.
	for len(params) > 0 && params[0] >= '0' && params[0] <= '9' {
		params = params[1:]
	}
	return params, mod
}

// decodeStandardCSI decodes a non-CSI-u sequence using the csiSeq lookup table.
func decodeStandardCSI(params string, final byte, mod, consumed int) (string, int) {
	seqKey := params + string(final)
	if key, ok := csiSeq[seqKey]; ok {
		if mod > 1 {
			return csiModPrefix(mod) + key, consumed
		}
		return key, consumed
	}
	if seqKey == "Z" {
		return KeyShiftTab, consumed
	}
	return "", consumed
}

// decodeCSIu decodes a Kitty CSI-u sequence (final byte = 'u').
// Formats:
//   - \x1b[A;1u (letter-based cursor keys)
//   - \x1b[OP;1u (SS3-style function keys)
//   - \x1b[3~;1u (tilde-based editing keys)
//   - \x1b[13;5u (numeric control codes with modifier)
//   - \x1b[97;1u (printable characters)
func decodeCSIu(data []byte, start, j, consumed, mod int) (string, int) {
	// Extract raw parameters from between ESC[ and the 'u' final byte
	fullParams := string(data[start+2 : j])
	codeEnd := strings.IndexByte(fullParams, ';')
	var ident string
	if codeEnd <= 0 {
		if len(fullParams) == 0 {
			return "", consumed
		}
		// No modifier part (e.g. \x1b[27u instead of \x1b[27;1u).
		// Use the entire params as the key identifier.
		ident = fullParams
	} else {
		ident = fullParams[:codeEnd] // key identifier before ';'
	}

	// 1) Letter-based identifiers: cursor keys (\x1b[A;1u) and SS3-style F-keys (\x1b[OP;1u)
	if ident[0] >= 'A' && ident[0] <= 'Z' {
		if key, ok := decodeCSIuLetterIdent(ident, mod); ok {
			return key, consumed
		}
		return "", consumed
	}

	// 2) Tilde-based codes: \x1b[3~;1u (Delete), \x1b[5~;1u (PageUp), etc.
	if key, ok := csiSeq[ident]; ok {
		if mod > 1 {
			return csiModPrefix(mod) + key, consumed
		}
		return key, consumed
	}

	// 4) Numeric control codes
	code := atoi(ident)
	if key, ok := decodeCSIuNumeric(code, mod); ok {
		return key, consumed
	}
	return "", consumed
}

// decodeCSIuLetterIdent handles letter-based CSI-u key identifiers.
// Supports single-letter cursor keys (\x1b[A;1u → "up") and SS3-style
// function keys (\x1b[OP;1u → "f1").
func decodeCSIuLetterIdent(ident string, mod int) (string, bool) {
	// Single-letter cursor/editing key
	if len(ident) == 1 {
		if key, ok := csiSeq[ident]; ok {
			if mod > 1 {
				return csiModPrefix(mod) + key, true
			}
			return key, true
		}
		return "", false
	}

	// SS3-style function key identifiers: OP (F1), OQ (F2), OR (F3), OS (F4)
	if len(ident) == 2 && ident[0] == 'O' && ident[1] >= 'P' && ident[1] <= 'S' {
		fkey := map[byte]string{
			'P': "f1", 'Q': "f2", 'R': "f3", 'S': "f4",
		}[ident[1]]
		if mod > 1 {
			return csiModPrefix(mod) + fkey, true
		}
		return fkey, true
	}

	return "", false
}

// decodeCSIuNumeric maps numeric key codes to key strings for CSI-u format.
func decodeCSIuNumeric(code, mod int) (string, bool) {
	switch {
	case code == 13:
		if mod > 1 {
			return csiModPrefix(mod) + KeyEnter, true
		}
		return KeyEnter, true
	case code == 27:
		// Kitty protocol may also report Escape as keycode 27 with various
		// modifiers. Regardless of modifier, treat it as Escape so the
		// wizard (and other components) can navigate back.
		return KeyEscape, true
	case code == 9:
		if mod > 1 {
			return csiModPrefix(mod) + KeyTab, true
		}
		return KeyTab, true
	case code == 8 || code == 127:
		return KeyBackspace, true
	case code >= 32 && code <= 126:
		ch := string(rune(code))
		if mod > 1 {
			return csiModPrefix(mod) + ch, true
		}
		return ch, true
	}
	return "", false
}

// atoi parses a string to int, returning 0 on error.
func atoi(s string) int {
	n := 0
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c < '0' || c > '9' {
			return n
		}
		n = n*10 + int(c-'0')
	}
	return n
}
