// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2026 Pierre Poissinger

// Code generated by go generate; DO NOT EDIT.
// Source: models.dev/api.json
package models

import "github.com/pijalu/goa/internal/agentic/provider"

func init() {
	loadGeneratedModels()
}

func loadGeneratedModels() {
	addModel(provider.Model{
		ID: "claude-fable-5", Name: "Claude Fable 5", Api: provider.Api("anthropic-messages"), Provider: provider.Provider("anthropic"),
		BaseURL:   "https://api.anthropic.com",
		Reasoning: true, ContextWindow: 1000000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000100000, Output: 0.0000500000, CacheRead: 0.0000010000, CacheWrite: 0.0000125000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "claude-haiku-4-5", Name: "Claude Haiku 4.5 (latest)", Api: provider.Api("anthropic-messages"), Provider: provider.Provider("anthropic"),
		BaseURL:   "https://api.anthropic.com",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 64000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000010000, Output: 0.0000050000, CacheRead: 0.0000001000, CacheWrite: 0.0000012500},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "claude-haiku-4-5-20251001", Name: "Claude Haiku 4.5", Api: provider.Api("anthropic-messages"), Provider: provider.Provider("anthropic"),
		BaseURL:   "https://api.anthropic.com",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 64000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000010000, Output: 0.0000050000, CacheRead: 0.0000001000, CacheWrite: 0.0000012500},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "claude-opus-4-1", Name: "Claude Opus 4.1 (latest)", Api: provider.Api("anthropic-messages"), Provider: provider.Provider("anthropic"),
		BaseURL:   "https://api.anthropic.com",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 32000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000150000, Output: 0.0000750000, CacheRead: 0.0000015000, CacheWrite: 0.0000187500},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "claude-opus-4-1-20250805", Name: "Claude Opus 4.1", Api: provider.Api("anthropic-messages"), Provider: provider.Provider("anthropic"),
		BaseURL:   "https://api.anthropic.com",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 32000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000150000, Output: 0.0000750000, CacheRead: 0.0000015000, CacheWrite: 0.0000187500},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "claude-opus-4-5", Name: "Claude Opus 4.5 (latest)", Api: provider.Api("anthropic-messages"), Provider: provider.Provider("anthropic"),
		BaseURL:   "https://api.anthropic.com",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 64000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000050000, Output: 0.0000250000, CacheRead: 0.0000005000, CacheWrite: 0.0000062500},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "claude-opus-4-5-20251101", Name: "Claude Opus 4.5", Api: provider.Api("anthropic-messages"), Provider: provider.Provider("anthropic"),
		BaseURL:   "https://api.anthropic.com",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 64000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000050000, Output: 0.0000250000, CacheRead: 0.0000005000, CacheWrite: 0.0000062500},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "claude-opus-4-6", Name: "Claude Opus 4.6", Api: provider.Api("anthropic-messages"), Provider: provider.Provider("anthropic"),
		BaseURL:   "https://api.anthropic.com",
		Reasoning: true, ContextWindow: 1000000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000050000, Output: 0.0000250000, CacheRead: 0.0000005000, CacheWrite: 0.0000062500},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "claude-opus-4-7", Name: "Claude Opus 4.7", Api: provider.Api("anthropic-messages"), Provider: provider.Provider("anthropic"),
		BaseURL:   "https://api.anthropic.com",
		Reasoning: true, ContextWindow: 1000000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000050000, Output: 0.0000250000, CacheRead: 0.0000005000, CacheWrite: 0.0000062500},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "claude-opus-4-8", Name: "Claude Opus 4.8", Api: provider.Api("anthropic-messages"), Provider: provider.Provider("anthropic"),
		BaseURL:   "https://api.anthropic.com",
		Reasoning: true, ContextWindow: 1000000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000050000, Output: 0.0000250000, CacheRead: 0.0000005000, CacheWrite: 0.0000062500},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "claude-sonnet-4-5", Name: "Claude Sonnet 4.5 (latest)", Api: provider.Api("anthropic-messages"), Provider: provider.Provider("anthropic"),
		BaseURL:   "https://api.anthropic.com",
		Reasoning: true, ContextWindow: 1000000, MaxTokens: 64000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000030000, Output: 0.0000150000, CacheRead: 0.0000003000, CacheWrite: 0.0000037500},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "claude-sonnet-4-5-20250929", Name: "Claude Sonnet 4.5", Api: provider.Api("anthropic-messages"), Provider: provider.Provider("anthropic"),
		BaseURL:   "https://api.anthropic.com",
		Reasoning: true, ContextWindow: 1000000, MaxTokens: 64000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000030000, Output: 0.0000150000, CacheRead: 0.0000003000, CacheWrite: 0.0000037500},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "claude-sonnet-4-6", Name: "Claude Sonnet 4.6", Api: provider.Api("anthropic-messages"), Provider: provider.Provider("anthropic"),
		BaseURL:   "https://api.anthropic.com",
		Reasoning: true, ContextWindow: 1000000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000030000, Output: 0.0000150000, CacheRead: 0.0000003000, CacheWrite: 0.0000037500},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "claude-sonnet-5", Name: "Claude Sonnet 5", Api: provider.Api("anthropic-messages"), Provider: provider.Provider("anthropic"),
		BaseURL:   "https://api.anthropic.com",
		Reasoning: true, ContextWindow: 1000000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000020000, Output: 0.0000100000, CacheRead: 0.0000002000, CacheWrite: 0.0000025000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "deepseek-chat", Name: "DeepSeek Chat", Api: provider.Api("openai-completions"), Provider: provider.Provider("deepseek"),
		BaseURL:   "https://api.deepseek.com",
		Reasoning: false, ContextWindow: 1000000, MaxTokens: 384000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000001400, Output: 0.0000002800, CacheRead: 0.0000000028, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "deepseek-reasoner", Name: "DeepSeek Reasoner", Api: provider.Api("openai-completions"), Provider: provider.Provider("deepseek"),
		BaseURL:   "https://api.deepseek.com",
		Reasoning: true, ContextWindow: 1000000, MaxTokens: 384000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000001400, Output: 0.0000002800, CacheRead: 0.0000000028, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "deepseek-v4-flash", Name: "DeepSeek V4 Flash", Api: provider.Api("openai-completions"), Provider: provider.Provider("deepseek"),
		BaseURL:   "https://api.deepseek.com",
		Reasoning: true, ContextWindow: 1000000, MaxTokens: 384000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000001400, Output: 0.0000002800, CacheRead: 0.0000000028, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "deepseek-v4-pro", Name: "DeepSeek V4 Pro", Api: provider.Api("openai-completions"), Provider: provider.Provider("deepseek"),
		BaseURL:   "https://api.deepseek.com",
		Reasoning: true, ContextWindow: 1000000, MaxTokens: 384000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000004350, Output: 0.0000008700, CacheRead: 0.0000000036, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-2.0-flash", Name: "Gemini 2.0 Flash", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: false, ContextWindow: 1048576, MaxTokens: 8192, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000001000, Output: 0.0000004000, CacheRead: 0.0000000250, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-2.0-flash-lite", Name: "Gemini 2.0 Flash-Lite", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: false, ContextWindow: 1048576, MaxTokens: 8192, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000000750, Output: 0.0000003000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 1048576, MaxTokens: 65536, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000003000, Output: 0.0000025000, CacheRead: 0.0000000300, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-2.5-flash-lite", Name: "Gemini 2.5 Flash-Lite", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 1048576, MaxTokens: 65536, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000001000, Output: 0.0000004000, CacheRead: 0.0000000100, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-2.5-pro", Name: "Gemini 2.5 Pro", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 1048576, MaxTokens: 65536, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000012500, Output: 0.0000100000, CacheRead: 0.0000001250, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-3-flash-preview", Name: "Gemini 3 Flash Preview", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 1048576, MaxTokens: 65536, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000005000, Output: 0.0000030000, CacheRead: 0.0000000500, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-3-pro-preview", Name: "Gemini 3 Pro Preview", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 1048576, MaxTokens: 65536, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000020000, Output: 0.0000120000, CacheRead: 0.0000002000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-3.1-flash-lite", Name: "Gemini 3.1 Flash Lite", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 1048576, MaxTokens: 65536, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000002500, Output: 0.0000015000, CacheRead: 0.0000000250, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-3.1-flash-lite-preview", Name: "Gemini 3.1 Flash Lite Preview", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 1048576, MaxTokens: 65536, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000002500, Output: 0.0000015000, CacheRead: 0.0000000250, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-3.1-pro-preview", Name: "Gemini 3.1 Pro Preview", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 1048576, MaxTokens: 65536, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000020000, Output: 0.0000120000, CacheRead: 0.0000002000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-3.1-pro-preview-customtools", Name: "Gemini 3.1 Pro Preview Custom Tools", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 1048576, MaxTokens: 65536, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000020000, Output: 0.0000120000, CacheRead: 0.0000002000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-3.5-flash", Name: "Gemini 3.5 Flash", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 1048576, MaxTokens: 65536, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000015000, Output: 0.0000090000, CacheRead: 0.0000001500, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-3.5-flash-lite", Name: "Gemini 3.5 Flash Lite", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 1048576, MaxTokens: 65536, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000003000, Output: 0.0000025000, CacheRead: 0.0000000300, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-3.6-flash", Name: "Gemini 3.6 Flash", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 1048576, MaxTokens: 65536, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000015000, Output: 0.0000075000, CacheRead: 0.0000001500, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-flash-latest", Name: "Gemini Flash Latest", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 1048576, MaxTokens: 65536, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000015000, Output: 0.0000090000, CacheRead: 0.0000001500, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemini-flash-lite-latest", Name: "Gemini Flash-Lite Latest", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 1048576, MaxTokens: 65536, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000002500, Output: 0.0000015000, CacheRead: 0.0000000250, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemma-4-26b-a4b-it", Name: "Gemma 4 26B A4B IT", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 262144, MaxTokens: 32768, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000000000, Output: 0.0000000000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gemma-4-31b-it", Name: "Gemma 4 31B IT", Api: provider.Api("google-generative-ai"), Provider: provider.Provider("google"),
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta",
		Reasoning: true, ContextWindow: 262144, MaxTokens: 32768, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000000000, Output: 0.0000000000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "llama-3.1-8b-instant", Name: "Llama 3.1 8B", Api: provider.Api("openai-completions"), Provider: provider.Provider("groq"),
		BaseURL:   "https://api.groq.com/openai/v1",
		Reasoning: false, ContextWindow: 131072, MaxTokens: 131072, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000000500, Output: 0.0000000800, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "llama-3.3-70b-versatile", Name: "Llama 3.3 70B", Api: provider.Api("openai-completions"), Provider: provider.Provider("groq"),
		BaseURL:   "https://api.groq.com/openai/v1",
		Reasoning: false, ContextWindow: 131072, MaxTokens: 32768, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000005900, Output: 0.0000007900, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "meta-llama/llama-4-scout-17b-16e-instruct", Name: "Llama 4 Scout 17B 16E", Api: provider.Api("openai-completions"), Provider: provider.Provider("groq"),
		BaseURL:   "https://api.groq.com/openai/v1",
		Reasoning: false, ContextWindow: 131072, MaxTokens: 8192, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000001100, Output: 0.0000003400, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "openai/gpt-oss-120b", Name: "GPT OSS 120B", Api: provider.Api("openai-completions"), Provider: provider.Provider("groq"),
		BaseURL:   "https://api.groq.com/openai/v1",
		Reasoning: true, ContextWindow: 131072, MaxTokens: 65536, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000001500, Output: 0.0000006000, CacheRead: 0.0000000750, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "openai/gpt-oss-20b", Name: "GPT OSS 20B", Api: provider.Api("openai-completions"), Provider: provider.Provider("groq"),
		BaseURL:   "https://api.groq.com/openai/v1",
		Reasoning: true, ContextWindow: 131072, MaxTokens: 65536, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000000750, Output: 0.0000003000, CacheRead: 0.0000000375, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "openai/gpt-oss-safeguard-20b", Name: "Safety GPT OSS 20B", Api: provider.Api("openai-completions"), Provider: provider.Provider("groq"),
		BaseURL:   "https://api.groq.com/openai/v1",
		Reasoning: true, ContextWindow: 131072, MaxTokens: 65536, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000000750, Output: 0.0000003000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "qwen/qwen3-32b", Name: "Qwen3-32B", Api: provider.Api("openai-completions"), Provider: provider.Provider("groq"),
		BaseURL:   "https://api.groq.com/openai/v1",
		Reasoning: true, ContextWindow: 131072, MaxTokens: 40960, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000002900, Output: 0.0000005900, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "codestral-latest", Name: "Codestral (latest)", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 256000, MaxTokens: 4096, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000003000, Output: 0.0000009000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "devstral-2512", Name: "Devstral 2", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 262144, MaxTokens: 262144, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000004000, Output: 0.0000020000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "devstral-latest", Name: "Devstral 2", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 262144, MaxTokens: 262144, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000004000, Output: 0.0000020000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "devstral-medium-2507", Name: "Devstral Medium", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 128000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000004000, Output: 0.0000020000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "devstral-medium-latest", Name: "Devstral 2 (latest)", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 262144, MaxTokens: 262144, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000004000, Output: 0.0000020000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "devstral-small-2505", Name: "Devstral Small 2505", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 128000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000001000, Output: 0.0000003000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "devstral-small-2507", Name: "Devstral Small", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 128000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000001000, Output: 0.0000003000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "labs-devstral-small-2512", Name: "Devstral Small 2", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 256000, MaxTokens: 256000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000000000, Output: 0.0000000000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "magistral-medium-latest", Name: "Magistral Medium (latest)", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: true, ContextWindow: 128000, MaxTokens: 16384, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000020000, Output: 0.0000050000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "magistral-small", Name: "Magistral Small", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: true, ContextWindow: 128000, MaxTokens: 128000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000005000, Output: 0.0000015000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "ministral-3b-latest", Name: "Ministral 3B (latest)", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 128000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000000400, Output: 0.0000000400, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "ministral-8b-latest", Name: "Ministral 8B (latest)", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 128000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000001000, Output: 0.0000001000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "mistral-large-2411", Name: "Mistral Large 2.1", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 131072, MaxTokens: 16384, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000020000, Output: 0.0000060000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "mistral-large-2512", Name: "Mistral Large 3", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 262144, MaxTokens: 262144, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000005000, Output: 0.0000015000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "mistral-large-latest", Name: "Mistral Large (latest)", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 262144, MaxTokens: 262144, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000005000, Output: 0.0000015000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "mistral-medium-2505", Name: "Mistral Medium 3", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 131072, MaxTokens: 131072, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000004000, Output: 0.0000020000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "mistral-medium-2508", Name: "Mistral Medium 3.1", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 262144, MaxTokens: 262144, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000004000, Output: 0.0000020000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "mistral-medium-2604", Name: "Mistral Medium 3.5", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: true, ContextWindow: 262144, MaxTokens: 262144, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000015000, Output: 0.0000075000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "mistral-medium-latest", Name: "Mistral Medium (latest)", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: true, ContextWindow: 262144, MaxTokens: 262144, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000015000, Output: 0.0000075000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "mistral-nemo", Name: "Mistral Nemo", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 128000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000001500, Output: 0.0000001500, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "mistral-small-2506", Name: "Mistral Small 3.2", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 16384, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000001000, Output: 0.0000003000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "mistral-small-2603", Name: "Mistral Small 4", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: true, ContextWindow: 256000, MaxTokens: 256000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000001500, Output: 0.0000006000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "mistral-small-latest", Name: "Mistral Small (latest)", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: true, ContextWindow: 256000, MaxTokens: 256000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000001500, Output: 0.0000006000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "open-mistral-7b", Name: "Mistral 7B", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 8000, MaxTokens: 8000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000002500, Output: 0.0000002500, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "open-mistral-nemo", Name: "Open Mistral Nemo", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 128000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000001500, Output: 0.0000001500, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "open-mixtral-8x22b", Name: "Mixtral 8x22B", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 64000, MaxTokens: 64000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000020000, Output: 0.0000060000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "open-mixtral-8x7b", Name: "Mixtral 8x7B", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 32000, MaxTokens: 32000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000007000, Output: 0.0000007000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "pixtral-12b", Name: "Pixtral 12B", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000001500, Output: 0.0000001500, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "pixtral-large-latest", Name: "Pixtral Large (latest)", Api: provider.Api("mistral-conversations"), Provider: provider.Provider("mistral"),
		BaseURL:   "https://api.mistral.ai",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000020000, Output: 0.0000060000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-4", Name: "GPT-4", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: false, ContextWindow: 8192, MaxTokens: 8192, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000300000, Output: 0.0000600000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-4-turbo", Name: "GPT-4 Turbo", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 4096, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000100000, Output: 0.0000300000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-4.1", Name: "GPT-4.1", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: false, ContextWindow: 1047576, MaxTokens: 32768, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000020000, Output: 0.0000080000, CacheRead: 0.0000005000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-4.1-mini", Name: "GPT-4.1 mini", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: false, ContextWindow: 1047576, MaxTokens: 32768, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000004000, Output: 0.0000016000, CacheRead: 0.0000001000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-4.1-nano", Name: "GPT-4.1 nano", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: false, ContextWindow: 1047576, MaxTokens: 32768, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000001000, Output: 0.0000004000, CacheRead: 0.0000000250, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-4o", Name: "GPT-4o", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 16384, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000025000, Output: 0.0000100000, CacheRead: 0.0000012500, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-4o-2024-05-13", Name: "GPT-4o (2024-05-13)", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 4096, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000050000, Output: 0.0000150000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-4o-2024-08-06", Name: "GPT-4o (2024-08-06)", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 16384, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000025000, Output: 0.0000100000, CacheRead: 0.0000012500, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-4o-2024-11-20", Name: "GPT-4o (2024-11-20)", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 16384, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000025000, Output: 0.0000100000, CacheRead: 0.0000012500, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-4o-mini", Name: "GPT-4o mini", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 16384, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000001500, Output: 0.0000006000, CacheRead: 0.0000000750, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5", Name: "GPT-5", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 400000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000012500, Output: 0.0000100000, CacheRead: 0.0000001250, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5-codex", Name: "GPT-5-Codex", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 400000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000012500, Output: 0.0000100000, CacheRead: 0.0000001250, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5-mini", Name: "GPT-5 Mini", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 400000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000002500, Output: 0.0000020000, CacheRead: 0.0000000250, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5-nano", Name: "GPT-5 Nano", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 400000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000000500, Output: 0.0000004000, CacheRead: 0.0000000050, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5-pro", Name: "GPT-5 Pro", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 400000, MaxTokens: 272000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000150000, Output: 0.0001200000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.1", Name: "GPT-5.1", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 400000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000012500, Output: 0.0000100000, CacheRead: 0.0000001250, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.1-chat-latest", Name: "GPT-5.1 Chat", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 128000, MaxTokens: 16384, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000012500, Output: 0.0000100000, CacheRead: 0.0000001250, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.1-codex", Name: "GPT-5.1 Codex", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 400000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000012500, Output: 0.0000100000, CacheRead: 0.0000001250, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.1-codex-max", Name: "GPT-5.1 Codex Max", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 400000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000012500, Output: 0.0000100000, CacheRead: 0.0000001250, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.1-codex-mini", Name: "GPT-5.1 Codex mini", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 400000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000002500, Output: 0.0000020000, CacheRead: 0.0000000250, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.2", Name: "GPT-5.2", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 400000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000017500, Output: 0.0000140000, CacheRead: 0.0000001750, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.2-chat-latest", Name: "GPT-5.2 Chat", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 128000, MaxTokens: 16384, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000017500, Output: 0.0000140000, CacheRead: 0.0000001750, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.2-codex", Name: "GPT-5.2 Codex", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 400000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000017500, Output: 0.0000140000, CacheRead: 0.0000001750, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.2-pro", Name: "GPT-5.2 Pro", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 400000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000210000, Output: 0.0001680000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.3-chat-latest", Name: "GPT-5.3 Chat (latest)", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: false, ContextWindow: 128000, MaxTokens: 16384, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000017500, Output: 0.0000140000, CacheRead: 0.0000001750, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.3-codex", Name: "GPT-5.3 Codex", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 400000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000017500, Output: 0.0000140000, CacheRead: 0.0000001750, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.3-codex-spark", Name: "GPT-5.3 Codex Spark", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 128000, MaxTokens: 32000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000017500, Output: 0.0000140000, CacheRead: 0.0000001750, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.4", Name: "GPT-5.4", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 1050000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000025000, Output: 0.0000150000, CacheRead: 0.0000002500, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.4-mini", Name: "GPT-5.4 mini", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 400000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000007500, Output: 0.0000045000, CacheRead: 0.0000000750, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.4-nano", Name: "GPT-5.4 nano", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 400000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000002000, Output: 0.0000012500, CacheRead: 0.0000000200, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.4-pro", Name: "GPT-5.4 Pro", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 1050000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000300000, Output: 0.0001800000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.5", Name: "GPT-5.5", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 1050000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000050000, Output: 0.0000300000, CacheRead: 0.0000005000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.5-pro", Name: "GPT-5.5 Pro", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 1050000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000300000, Output: 0.0001800000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.6", Name: "GPT-5.6", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 1050000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000050000, Output: 0.0000300000, CacheRead: 0.0000005000, CacheWrite: 0.0000062500},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.6-luna", Name: "GPT-5.6 Luna", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 1050000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000010000, Output: 0.0000060000, CacheRead: 0.0000001000, CacheWrite: 0.0000012500},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.6-sol", Name: "GPT-5.6 Sol", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 1050000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000050000, Output: 0.0000300000, CacheRead: 0.0000005000, CacheWrite: 0.0000062500},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-5.6-terra", Name: "GPT-5.6 Terra", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 1050000, MaxTokens: 128000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000025000, Output: 0.0000150000, CacheRead: 0.0000002500, CacheWrite: 0.0000031250},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "gpt-realtime-2.1", Name: "GPT-Realtime-2.1", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 128000, MaxTokens: 32000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000040000, Output: 0.0000240000, CacheRead: 0.0000004000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "o1", Name: "o1", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 100000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000150000, Output: 0.0000600000, CacheRead: 0.0000075000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "o1-pro", Name: "o1-pro", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 100000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0001500000, Output: 0.0006000000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "o3", Name: "o3", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 100000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000020000, Output: 0.0000080000, CacheRead: 0.0000005000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "o3-deep-research", Name: "o3-deep-research", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 100000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000100000, Output: 0.0000400000, CacheRead: 0.0000025000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "o3-mini", Name: "o3-mini", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 100000, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000011000, Output: 0.0000044000, CacheRead: 0.0000005500, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "o3-pro", Name: "o3-pro", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 100000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000200000, Output: 0.0000800000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "o4-mini", Name: "o4-mini", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 100000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000011000, Output: 0.0000044000, CacheRead: 0.0000002750, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "o4-mini-deep-research", Name: "o4-mini-deep-research", Api: provider.Api("openai-responses"), Provider: provider.Provider("openai"),
		BaseURL:   "https://api.openai.com/v1",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 100000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000020000, Output: 0.0000080000, CacheRead: 0.0000005000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "grok-4.20-0309-non-reasoning", Name: "Grok 4.20 (Non-Reasoning)", Api: provider.Api("openai-completions"), Provider: provider.Provider("xai"),
		BaseURL:   "https://api.x.ai/v1",
		Reasoning: false, ContextWindow: 1000000, MaxTokens: 30000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000012500, Output: 0.0000025000, CacheRead: 0.0000002000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "grok-4.20-0309-reasoning", Name: "Grok 4.20 (Reasoning)", Api: provider.Api("openai-completions"), Provider: provider.Provider("xai"),
		BaseURL:   "https://api.x.ai/v1",
		Reasoning: true, ContextWindow: 1000000, MaxTokens: 30000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000012500, Output: 0.0000025000, CacheRead: 0.0000002000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "grok-4.3", Name: "Grok 4.3", Api: provider.Api("openai-completions"), Provider: provider.Provider("xai"),
		BaseURL:   "https://api.x.ai/v1",
		Reasoning: true, ContextWindow: 1000000, MaxTokens: 30000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000012500, Output: 0.0000025000, CacheRead: 0.0000002000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "grok-4.5", Name: "Grok 4.5", Api: provider.Api("openai-completions"), Provider: provider.Provider("xai"),
		BaseURL:   "https://api.x.ai/v1",
		Reasoning: true, ContextWindow: 500000, MaxTokens: 500000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000020000, Output: 0.0000060000, CacheRead: 0.0000003000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "grok-build-0.1", Name: "Grok Build 0.1", Api: provider.Api("openai-completions"), Provider: provider.Provider("xai"),
		BaseURL:   "https://api.x.ai/v1",
		Reasoning: true, ContextWindow: 256000, MaxTokens: 256000, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000010000, Output: 0.0000020000, CacheRead: 0.0000002000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-4.5", Name: "GLM-4.5", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai-api"),
		BaseURL:   "https://api.z.ai/api/paas/v4",
		Reasoning: true, ContextWindow: 131072, MaxTokens: 98304, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000006000, Output: 0.0000022000, CacheRead: 0.0000001100, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-4.5-air", Name: "GLM-4.5-Air", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai-api"),
		BaseURL:   "https://api.z.ai/api/paas/v4",
		Reasoning: true, ContextWindow: 131072, MaxTokens: 98304, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000002000, Output: 0.0000011000, CacheRead: 0.0000000300, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-4.5-flash", Name: "GLM-4.5-Flash", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai-api"),
		BaseURL:   "https://api.z.ai/api/paas/v4",
		Reasoning: true, ContextWindow: 131072, MaxTokens: 98304, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000000000, Output: 0.0000000000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-4.5v", Name: "GLM-4.5V", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai-api"),
		BaseURL:   "https://api.z.ai/api/paas/v4",
		Reasoning: true, ContextWindow: 64000, MaxTokens: 16384, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000006000, Output: 0.0000018000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-4.6", Name: "GLM-4.6", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai-api"),
		BaseURL:   "https://api.z.ai/api/paas/v4",
		Reasoning: true, ContextWindow: 204800, MaxTokens: 131072, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000006000, Output: 0.0000022000, CacheRead: 0.0000001100, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-4.6v", Name: "GLM-4.6V", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai-api"),
		BaseURL:   "https://api.z.ai/api/paas/v4",
		Reasoning: true, ContextWindow: 128000, MaxTokens: 32768, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000003000, Output: 0.0000009000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-4.7", Name: "GLM-4.7", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai-api"),
		BaseURL:   "https://api.z.ai/api/paas/v4",
		Reasoning: true, ContextWindow: 204800, MaxTokens: 131072, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000006000, Output: 0.0000022000, CacheRead: 0.0000001100, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-4.7-flash", Name: "GLM-4.7-Flash", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai-api"),
		BaseURL:   "https://api.z.ai/api/paas/v4",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 131072, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000000000, Output: 0.0000000000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-4.7-flashx", Name: "GLM-4.7-FlashX", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai-api"),
		BaseURL:   "https://api.z.ai/api/paas/v4",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 131072, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000000700, Output: 0.0000004000, CacheRead: 0.0000000100, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-5", Name: "GLM-5", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai-api"),
		BaseURL:   "https://api.z.ai/api/paas/v4",
		Reasoning: true, ContextWindow: 204800, MaxTokens: 131072, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000010000, Output: 0.0000032000, CacheRead: 0.0000002000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-5-turbo", Name: "GLM-5-Turbo", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai-api"),
		BaseURL:   "https://api.z.ai/api/paas/v4",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 131072, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000012000, Output: 0.0000040000, CacheRead: 0.0000002400, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-5.1", Name: "GLM-5.1", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai-api"),
		BaseURL:   "https://api.z.ai/api/paas/v4",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 131072, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000014000, Output: 0.0000044000, CacheRead: 0.0000002600, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-5.2", Name: "GLM-5.2", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai-api"),
		BaseURL:   "https://api.z.ai/api/paas/v4",
		Reasoning: true, ContextWindow: 1000000, MaxTokens: 131072, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000014000, Output: 0.0000044000, CacheRead: 0.0000002600, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-5v-turbo", Name: "GLM-5V-Turbo", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai-api"),
		BaseURL:   "https://api.z.ai/api/paas/v4",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 131072, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000012000, Output: 0.0000040000, CacheRead: 0.0000002400, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-4.5-air", Name: "GLM-4.5-Air", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai"),
		BaseURL:   "https://api.z.ai/api/coding/paas/v4",
		Reasoning: true, ContextWindow: 131072, MaxTokens: 98304, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000000000, Output: 0.0000000000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-4.7", Name: "GLM-4.7", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai"),
		BaseURL:   "https://api.z.ai/api/coding/paas/v4",
		Reasoning: true, ContextWindow: 204800, MaxTokens: 131072, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000000000, Output: 0.0000000000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-5-turbo", Name: "GLM-5-Turbo", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai"),
		BaseURL:   "https://api.z.ai/api/coding/paas/v4",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 131072, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000000000, Output: 0.0000000000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-5.1", Name: "GLM-5.1", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai"),
		BaseURL:   "https://api.z.ai/api/coding/paas/v4",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 131072, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000000000, Output: 0.0000000000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-5.2", Name: "GLM-5.2", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai"),
		BaseURL:   "https://api.z.ai/api/coding/paas/v4",
		Reasoning: true, ContextWindow: 1000000, MaxTokens: 131072, InputTypes: []string{"text"},
		Cost:           provider.ModelPricing{Input: 0.0000000000, Output: 0.0000000000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
	addModel(provider.Model{
		ID: "glm-5v-turbo", Name: "GLM-5V-Turbo", Api: provider.Api("openai-completions"), Provider: provider.Provider("zai"),
		BaseURL:   "https://api.z.ai/api/coding/paas/v4",
		Reasoning: true, ContextWindow: 200000, MaxTokens: 131072, InputTypes: []string{"text", "image"},
		Cost:           provider.ModelPricing{Input: 0.0000000000, Output: 0.0000000000, CacheRead: 0.0000000000, CacheWrite: 0.0000000000},
		ThinkingFormat: provider.ThinkingFormatNone,
	})
}
