// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2026 Pierre Poissinger

package multiagent

import (
	"testing"

	"github.com/pijalu/goa/internal/agentic/provider"
)

func TestParseTasks_Empty(t *testing.T) {
	tasks := ParseTasks("")
	if len(tasks) != 0 {
		t.Errorf("expected 0 tasks, got %d", len(tasks))
	}
}

func TestParseTasks_Single(t *testing.T) {
	tasks := ParseTasks("Refactor database layer")
	if len(tasks) != 1 {
		t.Fatalf("expected 1 task, got %d", len(tasks))
	}
	if tasks[0].Description != "Refactor database layer" {
		t.Errorf("expected 'Refactor database layer', got %q", tasks[0].Description)
	}
	if tasks[0].Status != TaskPending {
		t.Errorf("expected TaskPending status, got %v", tasks[0].Status)
	}
	if tasks[0].ID == "" {
		t.Error("expected non-empty task ID")
	}
}

func TestParseTasks_Multiple(t *testing.T) {
	tasks := ParseTasks("Build auth system, Add rate limiting, Write tests")
	if len(tasks) != 3 {
		t.Fatalf("expected 3 tasks, got %d", len(tasks))
	}
	if tasks[0].Description != "Build auth system" {
		t.Errorf("expected 'Build auth system', got %q", tasks[0].Description)
	}
	if tasks[1].Description != "Add rate limiting" {
		t.Errorf("expected 'Add rate limiting', got %q", tasks[1].Description)
	}
	if tasks[2].Description != "Write tests" {
		t.Errorf("expected 'Write tests', got %q", tasks[2].Description)
	}
}

func TestParseTasks_TrailingComma(t *testing.T) {
	tasks := ParseTasks("task1, task2, ")
	if len(tasks) != 2 {
		t.Errorf("expected 2 tasks (trailing comma trimmed), got %d", len(tasks))
	}
}

func TestParseTasks_TaskIDs_AutoGenerated(t *testing.T) {
	tasks := ParseTasks("A, B, C")
	if len(tasks) != 3 {
		t.Fatalf("expected 3 tasks, got %d", len(tasks))
	}
	for i, task := range tasks {
		expectedID := "task-1"
		if i == 1 {
			expectedID = "task-2"
		} else if i == 2 {
			expectedID = "task-3"
		}
		if task.ID != expectedID {
			t.Errorf("task %d: expected ID %q, got %q", i, expectedID, task.ID)
		}
	}
}

func TestSplitTaskDescriptions_Empty(t *testing.T) {
	result := splitTaskDescriptions("")
	if len(result) != 0 {
		t.Errorf("expected 0 descriptions, got %d", len(result))
	}
}

func TestSplitTaskDescriptions_Multiple(t *testing.T) {
	result := splitTaskDescriptions(" a, b ,c ")
	if len(result) != 3 {
		t.Fatalf("expected 3 descriptions, got %d", len(result))
	}
	if result[0] != "a" {
		t.Errorf("expected 'a', got %q", result[0])
	}
	if result[1] != "b" {
		t.Errorf("expected 'b', got %q", result[1])
	}
	if result[2] != "c" {
		t.Errorf("expected 'c', got %q", result[2])
	}
}

func TestTrimSpace(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"  hello  ", "hello"},
		{"\t\thello\t", "hello"},
		{"hello", "hello"},
		{"", ""},
		{"   ", ""},
		{"a", "a"},
	}
	for _, tt := range tests {
		result := trimSpace(tt.input)
		if result != tt.expected {
			t.Errorf("trimSpace(%q) = %q, want %q", tt.input, result, tt.expected)
		}
	}
}

func TestTaskOrchestrator_New(t *testing.T) {
	pool := NewAgentPool(testModel("test-model"), provider.StreamOptions{}, nil)
	orch := NewForegroundOrchestrator(pool)
	to := NewTaskOrchestrator(orch)

	if to == nil {
		t.Fatal("NewTaskOrchestrator returned nil")
	}
	if to.ForegroundOrchestrator != orch {
		t.Error("expected stored orchestrator reference")
	}
	if to.current != -1 {
		t.Errorf("expected current=-1, got %d", to.current)
	}
}

func TestTaskOrchestrator_Tasks_Empty(t *testing.T) {
	pool := NewAgentPool(testModel("test-model"), provider.StreamOptions{}, nil)
	orch := NewForegroundOrchestrator(pool)
	to := NewTaskOrchestrator(orch)

	tasks := to.Tasks()
	if tasks != nil {
		t.Errorf("expected nil, got %v", tasks)
	}
}

func TestTaskOrchestrator_Current_Default(t *testing.T) {
	pool := NewAgentPool(testModel("test-model"), provider.StreamOptions{}, nil)
	orch := NewForegroundOrchestrator(pool)
	to := NewTaskOrchestrator(orch)

	if to.Current() != -1 {
		t.Errorf("expected -1, got %d", to.Current())
	}
}

func TestTaskOrchestrator_Progress_Empty(t *testing.T) {
	pool := NewAgentPool(testModel("test-model"), provider.StreamOptions{}, nil)
	orch := NewForegroundOrchestrator(pool)
	to := NewTaskOrchestrator(orch)

	cur, total := to.Progress()
	if cur != 0 || total != 0 {
		t.Errorf("expected (0,0), got (%d,%d)", cur, total)
	}
}

func TestTaskStatus_String(t *testing.T) {
	tests := []struct {
		status   TaskStatus
		expected string
	}{
		{TaskPending, "pending"},
		{TaskPlanning, "planning"},
		{TaskCoding, "coding"},
		{TaskTesting, "testing"},
		{TaskReviewing, "reviewing"},
		{TaskComplete, "complete"},
		{TaskFailed, "failed"},
		{TaskStatus(99), "unknown"},
	}
	for _, tt := range tests {
		if tt.status.String() != tt.expected {
			t.Errorf("TaskStatus(%d).String() = %q, want %q", tt.status, tt.status.String(), tt.expected)
		}
	}
}
